//	This library (ssd1306 driven oled display) is adapted for use with
//  Stm32 microcontrollers and the HAL i2c library.
//
//	The library is required 2 files (fonts.c/h) that contains 3 fonts.
//
#ifndef _SSD1306
#define _SSD1306

#include "stm32f1xx_hal.h"
#include "fonts.h"  //	- Font_7x10
					//	- Font_11x18
					//  - Font_16x26

// i2c port name in the main program generated by CubeMX
#define SSD1306_I2C_PORT		hi2c1
// I2C address 
#define SSD1306_I2C_ADDR        0x78
// SSD1306 width in pixels
#define SSD1306_WIDTH           128
// SSD1306 LCD height in pixels
#define SSD1306_HEIGHT          64

//	Alignment
typedef enum {
	_Left,        /* Started from left to right  */
	_Right       /*  Started from right to left */
} SSD1306_ALIGNMENT;

//	Color of pixel.
typedef enum {
	_Black,
	_White
} SSD1306_COLOR;

typedef struct {
	uint16_t CurrentX;
	uint16_t CurrentY;
	//uint8_t Inverted; // TODO What about decide which color to use in run-time.
	uint8_t Initialized;
} SSD1306_t;

extern I2C_HandleTypeDef SSD1306_I2C_PORT;

//	Public functions
void ssd1306_Init(void);
void ssd1306_Fill(SSD1306_COLOR color);
void ssd1306_UpdateScreen(void);
void ssd1306_DrawPixel(uint8_t x, uint8_t y, SSD1306_COLOR color);
char ssd1306_WriteChar(char ch, FontDef Font, SSD1306_COLOR color, SSD1306_ALIGNMENT alignment);
char ssd1306_WriteString(char* str, FontDef Font, SSD1306_COLOR color);
void ssd1306_WriteUnsignedInt(uint32_t value, FontDef Font, SSD1306_COLOR color);
void ssd1306_SetCursor(uint8_t x, uint8_t y);

#endif /* _SSD1306 */
